<?php
/**
 * @file
 * addfullajax
 * Add FullAjax library to Drupal 7
 * @since 2011.05.19
 *
 */

/**
 * Define default configuration
 * @todo rewrite animation
 */
function _addfullajax_def_values($name) {
  $def = array(
    'conf_base' => "
/* fullAjaxId - it content id, that generated based on the main region settings */
var filterUrl = ['/admin/','/logout','node/add','/edit'];
var filterQuery = ['q=admin','q=user/logout'];
FLAX.Filter.add({url:'/', id:fullAjaxId});
FLAX.Filter.add({url:filterUrl, query:filterQuery, type:'nowrap'});
FLAX.directLink();
FLAX.linkEqual[':ax:'+fullAjaxId+':'] = '!';
FLAX.linkEqual['[~q~]'] = '?';
FLAX.Filter.on('beforewrap', function(ops){
var regExt = /.+\.(jpg|jpeg|gif|png|mp3|mp4|ogg|ogv|webm|pdf|txt|odf|ods)$/i;
if (regExt.test(ops.el.href) || ops.el.nodeName == 'FORM' || ops.el.href.indexOf('/edit') != -1 || ops.el.href.indexOf('/add') != -1){return false;}
});
FLAX.Html.onall('unload', function(o){
  /* here can insert code for execut before content unloaded */
  Drupal.detachBehaviors('#'+fullAjaxId);
});
FLAX.Html.onall('load', function(o){
  /* here can insert code for execut after content loaded */
  Drupal.attachBehaviors('#'+fullAjaxId);
});
",
    'conf_anim' => "
FLAX.Effect.add({id:fullAjaxId, start: function(id, request){
 var mId = jQuery('#'+fullAjaxId), mIdWidth = mId.width(), mIdHeight = mId.height();
 if (!jQuery('#fullAjaxGif').length){
  jQuery('<img/>',{
   'id':'fullAjaxGif',
   'src':'sites/all/modules/addfullajax/images/ajax-loader.gif',
   'alt':'Loading...',
   'style':'position:absolute;border:none;padding:0;margin-left:'+ mIdWidth*0.5 +'px;top:'+ mIdHeight*0.3 +'px;'
  }).insertBefore(mId);
 };
 mId.fadeOut(300,request());
},
end: function(id){
 if (jQuery('#fullAjaxGif').length){jQuery('#fullAjaxGif').remove();};
 jQuery('#'+fullAjaxId).fadeIn(300);
}
});
"
  );
  return $def[$name];
}

/**
 * Implements hook_help().
 */
function addfullajax_help($path, $arg) {
  switch ($path) {
    case 'admin/help#addfullajax':
      return t('Help For FullAjax module.') . 'Advanced on <a href="https://github.com/Fedik/FullAJAX" target="_blank">github.com/Fedik/FullAJAX</a>';
  }
}
/**
 * Implements hook_permission().
 */
function addfullajax_permission() {
  return array(
    'administer addfullajax'  =>  array(
      'title'  =>  t('Administer the module'),
      'description'  =>  t('Perform maintenance tasks for the Add FullAjax module.'),
    ),
  );
}
/**
 * Implements hook_menu().
 */
function addfullajax_menu() {
  $items = array();

  $items['admin/config/development/addfullajax'] = array(
    'title'  =>  'Add FullAjax',
    'description'  =>  'Configuration for Add FullAjax module',
    'page callback'  =>  'drupal_get_form',
    'page arguments'  =>  array('addfullajax_admin_form'),
    'access arguments'  =>  array('administer addfullajax'),
    'type'  =>  MENU_NORMAL_ITEM,
    'file' => 'addfullajax.admin.inc'
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function addfullajax_init() {
  global $_addfullajax_need_ajax_response;

  //check whether we allow use fullajax sripts
  if (!_addfullajax_is_allow()) {
    $_addfullajax_need_ajax_response = FALSE;
    return ;
  }

  if ((isset($_SERVER['HTTP_AJAX_ENGINE']) && $_SERVER['HTTP_AJAX_ENGINE'] == 'Fullajax')
    || (isset($_REQUEST['ax']) && $_REQUEST['ax'] == 'ok' )
  ) {
    $_addfullajax_need_ajax_response = TRUE;
    return ;
  }

  _addfullajax_add_config_js();

}

/**
 * check whether we allow use fullajax sripts
 * @return boolean
 */
function _addfullajax_is_allow() {
  //check whether allow for templates
  global $theme_key;
  $themes_disabled = variable_get('addfullajax_themes_disabled', array('seven'));

  if (!empty($themes_disabled[$theme_key])) {
    return FALSE;
  }

  if (arg(0) == 'admin' || arg(1) == 'add' || arg(2) == 'edit'
    || stristr(request_path(), 'media/browser')) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Add JS Configuration for FullAjax
 */
function _addfullajax_add_config_js() {

  $dbg = variable_get('addfullajax_debug');

  //Add base JS
  $lib_path = libraries_get_path('fullajax');
  drupal_add_js($lib_path . '/fullajax.js');

  //$theme_default = variable_get('theme_default', 'bartik');
  //$main_region = variable_get('addfullajax_themes_' . $theme_default . '_main_region', 'content');

  $js  = "var fullAjaxId = '" . variable_get('addfullajax_cssid', 'forajax') . "';\n";
  $js .= variable_get('addfullajax_data', _addfullajax_def_values('conf_base'));
  $js .= variable_get('addfullajax_animation', _addfullajax_def_values('conf_anim'));

  if (!variable_get('addfullajax_use_html5', 1)) {
    $js .= "\nFLAX.Default.USE_HTML5_HISTORY = 0;";
  }

  if (variable_get('addfullajax_checkmenuit', 1)) {
    $js .= "\n/* Change active menu item */
FLAX.Html.onall('load', function(o){
 jQuery('ul .active').removeClass('active active-trail');
 jQuery('ul li a[href=\"'+o.url+'\"]').addClass('active active-trail').parent().addClass('active active-trail');
});";}
  if (variable_get('addfullajax_useGA', 0)) {
    $js .= "\nFLAX.Html.onall('load', function(o){ _gaq.push(['_trackPageview', o.url]); });";
  }
  if (!variable_get('addfullajax_usr_cache', 1)) {
    $js .= "\nFLAX.Default.HAX_ANTICACHE = 1;FLAX.Default.USE_HISTORY_CACHE = 0;";
  }
  if ($dbg['debug_ajax']) {
    $js .= "\nFLAX.Default.DEBUG_AJAX=1;";
  }
  if ($dbg['debug_script']) {
    $js .= "\nFLAX.Default.DEBUG_SCRIPT=1;";
  }
  if ($dbg['debug_link']) {
    $js .= "\nFLAX.Default.DEBUG_LINK=1;";
  }
  if ($dbg['debug_style']) {
    $js .= "\nFLAX.Default.DEBUG_STYLE=1;";
  }

  drupal_add_js($js, array('type'  =>  'inline', 'weight'  =>  300));

}
/**
 * Generate JavaScript for FullAJAX Model2Blocks
 * @todo allow interaction with themes/modules here
 * @param array $markers - array with block ids
 */
function _addfullajax_add_model2bloks($markers) {
  $m2b = array();

  foreach (array_unique($markers) as $block) {
    $m2b [] = '\'' . $block . '\':\'' . $block . '\'';
  }
  $js  = 'FLAX.Model2Blocks[fullAjaxId] = {' . implode(',', $m2b) . '};';

  drupal_add_js($js, array('type'  =>  'inline', 'weight'  =>  301));
}

/**
* Implements hook_theme().
* add own theme
*/
function addfullajax_theme() {
  return array(
    //theme for render FullAJAX answer
    'addfullajax_page' => array(
      'render element' => 'page',
      'template' => 'addfullajax-page',
    ),
  );
}
/**
 * preprocess for theme_addfullajax_page
 * need for apply all variables for page from preprocess_page
 * @param array $variables
 */
function template_preprocess_addfullajax_page(&$variables) {
  template_preprocess_page($variables);
}
/**
 * process for theme_addfullajax_page
 * add couple new variables: regions - regions that need render, not allowed was removed in addfullajax_page_alter
 * @param array $variables
 */
function template_process_addfullajax_page(&$variables) {
  //apply page variables
  template_process_page($variables);

  $theme_default = variable_get('theme_default', 'bartik');
  $variables['main_region'] = variable_get('addfullajax_themes_' . $theme_default . '_main_region', 'content');
  $variables['regions'] = $variables['page']['#addfullajax_regions'];

  $variables['content_id'] = variable_get('addfullajax_cssid', 'forajax');
}

/**
 * theme for render a page for fullajax answer
 * not used
 * @see addfullajax-page.tpl.php file
 * @param array $variables
 */
function theme_addfullajax_page(&$variables) {
  $output = '';
  //render regions
  foreach ($variables['regions'] as $region) {
    if ($region == $main_region) {
      $output .= '<!-- :ax:' . $variables['content_id'] . ':begin: //-->';
      $output .= render($variables['page'][$region]);
      $output .= '<!-- :ax:' . $variables['content_id'] . ':end: //-->';
    }
    else {
      $output .= '<!-- :ax:flax-' . $region . ':begin: //-->';
      $output .= render($variables['page'][$region]);
      $output .= '<!-- :ax:flax-' . $region . ':end: //-->';
    }
  }
  return $output;
}

/**
 * Implements hook_page_alter(&$page).
 * Remove regions that no need to send again
 */

function addfullajax_page_alter(&$page) {
  global $_addfullajax_need_ajax_response;

  $content_id = variable_get('addfullajax_cssid', 'forajax');

  $theme_default = variable_get('theme_default', 'bartik');
  $allowed_regions = variable_get('addfullajax_themes_' . $theme_default . '_regions', array('content' => 'content'));
  $main_region = variable_get('addfullajax_themes_' . $theme_default . '_main_region', 'content');
  //just in case
  $allowed_regions[$main_region] = $main_region;

  if ($_addfullajax_need_ajax_response) {
    //use own theme for answer
    $page['#theme'] = 'addfullajax_page';
    //$page['#theme_wrappers'] = array('addfullajax_html');
    $page['#addfullajax_regions'] = array();

    //remove regions that no need render
    foreach (element_children($page) as $key) {
      if (empty($allowed_regions[$key])) {
        unset($page[$key]);
      }
      else {
        $page['#addfullajax_regions'][] = $key;
      }
    }

  }
  else {//add markers
    $regions = array($content_id);

    foreach ($allowed_regions as $r) {
      //add wrapers only for additional regions
      //ignore main region, and regins that empty
      if (isset($page[$r]) && $r != $main_region) {

        $page[$r]['#prefix'] = empty($page[$r]['#prefix']) ? '<div id="flax-' . $r . '">' : '<div id="flax-' . $r . '">' . $page[$r]['#prefix'];
        $page[$r]['#suffix'] = empty($page[$r]['#suffix']) ? '</div>' : $page[$r]['#suffix'] . '</div>';
        //collect only alloved regions
        $regions[] = 'flax-' . $r;
      }
    }
    //add Model2Blocks if more than one region
    $count = count($regions);
    if ($count && $count > 1) {
      _addfullajax_add_model2bloks($regions);
    }
  }
}

